service: dynamodb-local

frameworkVersion: "2"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  endpointType: REGIONAL
  runtime: python3.8
  versionFunctions: true
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-northeast-1

package:
  individually: true
  exclude:
    - config/**
    - functions/**
    - README.md

functions:
  scan:
    handler: functions/scan/handler.scan
    memorySize: 128
    timeout: 60
    package:
      individually: true
      include: functions/scan/*

plugins:
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    DynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: TestUsersTable-${self:provider.stage}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: dev
    seed:
      dev:
        sources:
          - table: TestUsersTable-dev
            sources:
              - ./seeds/TestUsersTable-dev.json
