service: python-requirements-one-req-txt

frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-northeast-1
  environment:
    STAGE: ${self:provider.stage}

package:
  individually: true
  exclude:
    - config/**
    - functions/**
    - README.md

functions:
  func1:
    handler: functions/func1/handler.func1
    memorySize: 128
    timeout: 3
    package:
      individually: true
      include:
        functions/func1/*
    layers:
      - Ref: PythonRequirementsLambdaLayer

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true
    layer:
      name: ${self:provider.stage}-numpy
      description: numpy for the python-requirements-one-req-txt project
      compatibleRuntimes:
        - python3.8
      licenseInfo: 
