service: s3-local

frameworkVersion: "2"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  endpointType: REGIONAL
  runtime: python3.8
  versionFunctions: true
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-northeast-1

package:
  individually: true
  exclude:
    - config/**
    - functions/**
    - README.md

functions:
  put_object:
    handler: functions/put_object/handler.put_object
    memorySize: 128
    timeout: 3
    package:
      individually: true
      include: functions/put_object/*
    role: S3Test
  get_object:
    handler: functions/get_object/handler.get_object
    memorySize: 128
    timeout: 3
    package:
      individually: true
      include: functions/get_object/*
    role: S3Test

plugins:
  - serverless-s3-local
  - serverless-offline

resources:
  Resources:
    S3Test:
      Type: AWS::IAM::Role
      Properties:
        RoleName: S3Test
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: S3TestPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:PutObject"
                    - "s3:PutObjectAcl"
                    - "s3:GetObject"
                    - "s3:GetObjectAcl"
                  Resource:
                    - "arn:aws:s3:::s3-local-test-bucket/*"

custom:
  s3:
    host: localhost
    directory: /tmp
  resources:
    Resources:
      NewResource:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: local-bucket
  functions:
    webhook:
      handler: handler.webhook
      events:
        - http:
          method: GET
          path: /
    s3hook:
      handler: handler.s3hook
      events:
        - s3: local-bucket
          event: s3:*
