service: local-schedule

frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  versionFunctions: true
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: ap-northeast-1
  environment:
    STAGE: ${self:provider.stage}

package:
  individually: true
  exclude:
    - config/**
    - functions/**
    - README.md

functions:
  put:
    handler: functions/put/handler.put
    memorySize: 128
    timeout: 3
    events:
      - schedule:
          # rate: cron(0/1 * * * ? *) # every minute # cron has not supported!!!
          rate: rate(1 minutes) # every minute
    package:
      individually: true
      include:
        functions/put/*
  scan:
    handler: functions/scan/handler.scan
    memorySize: 128
    timeout: 10
    package:
      individually: true
      include:
        functions/scan/*


resources:
  Resources:
    DynamoDbTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            AttributeDefinitions:
                - AttributeName: timestamp
                  AttributeType: N
            KeySchema:
                - AttributeName: timestamp
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: TestScheduleTable-${self:provider.stage}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-local-schedule
  - serverless-dynamodb-local
  - serverless-offline
